shared_configs:
  simple_job_steps: &simple_job_steps
    - checkout
    - run:
        name: Run tests
        command: |
          make -C errgroup test
          make -C eventstream test
          make -C eventstream/test test


# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build-1-20:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.20
    steps: *simple_job_steps

  build-1-21:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.21
    steps: *simple_job_steps

  build-1-22:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.22
    steps: *simple_job_steps

  build-1-23:
    working_directory: ~/repo
    docker:
      - image: cimg/go:1.23
    steps:
      - checkout
      - run:
          name: Run tests and linters
          command: |
            make -C errgroup ci
            make -C eventstream ci
            make -C eventstream/test ci

workflows:
  pr-build-test:
    jobs:
      - build-1-20
      - build-1-21
      - build-1-22
      - build-1-23
